# Generated by Django 2.2.9 on 2020-01-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kirim',
            old_name='price',
            new_name='price_in_RM',
        ),
        migrations.RemoveField(
            model_name='kirim',
            name='available_units',
        ),
        migrations.AddField(
            model_name='kirim',
            name='available_units_in_kg',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kirim',
            name='title',
            field=models.CharField(default='kiriman', max_length=120),
        ),
        migrations.AlterField(
            model_name='kirim',
            name='location',
            field=models.CharField(default='kiriman', max_length=120),
        ),
    ]
