# Generated by Django 2.2.9 on 2020-01-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200122_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirim',
            name='location',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='kirim',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
