# Generated by Django 2.2.9 on 2020-01-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200122_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kirim',
            old_name='kirim_destination',
            new_name='destination',
        ),
    ]
